[package]
name = "counter_simulator"
version = "0.1.0"
authors = ["Paulo Sérgio Almeida <pssalmeida@gmail.com>"]

[dependencies]
devesim = { git = "https://github.com/pssalmeida/devesim-rs.git" }
handoff_counter = "0.8"
rand = "0.3.14"
roaring = "0.4.0"
